import "dotenv/config";
import { PrismaClient } from "../src/generated/prisma/client.js";
import { PrismaPg } from "@prisma/adapter-pg";
import pg from "pg";
import bcrypt from "bcryptjs";

const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL! });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

async function main() {
  console.log("🌱 Seeding database...");

  // ── Admin user ──────────────────────────────────────────────────────
  const passwordHash = await bcrypt.hash("admin2024!", 12);
  await prisma.adminUser.upsert({
    where: { email: "admin@ristointour.it" },
    update: {},
    create: {
      email: "admin@ristointour.it",
      passwordHash,
      name: "Admin",
      role: "admin",
    },
  });
  console.log("✅ Admin user created (admin@ristointour.it / admin2024!)");

  // ── Listings (restaurants, agriturismi, etc.) ───────────────────────
  const listings = [
    {
      slug: "la-dispensa-di-san-salvatore",
      name: "La Dispensa di San Salvatore",
      category: "ristorante",
      planType: "premium",
      location: "Paestum, Campania",
      description: "Cucina Tradizionale & Caseificio",
      cuisine: "Cucina Cilentana Tradizionale",
      badge: "Premium",
      badgeStyle: "bg-white/90 backdrop-blur text-emerald-900",
      showOnHomepage: true,
      hasDetailPage: true,
      displayPriority: 1,
      featured: true,
      status: "published",
      image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDCIzWJuRfMbRDrHetzmCGaEWJf5SW-MBK7rvE2LFn_96T8aXMcog7UIicLiTgrgH7M0q0eisa6LdQr8a3Bla8w_RNFaFdwpSfBkvV-rlqQICmGmPDTP_z51NQqTopSD6BWBb8raXwkqkAsNx3FU_vWG-_hhgfdU8obpmDPcljPgBxLSbQPFjqXrPfD1WqAdmdqDYsTaBc3eF-jw5TjndNatLrIxhAAdwvZ4LLUkPLhQ9k9mKaaaZnVUpY1I8tHbxOhzK6a51tqoRuV",
      heroImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuBWNzsawD_laLLp2VTmZFfFI_OGM7wiSJ6SAxHvNMUgfriHjXgaUrIW7jgHbDd475taZR6ztBuq0opb3xSSQOseSzUHTBfC-hwJ4Cm8kwev_cfqFC0Ib-0Frxw5rm-LNBUJD1E8f3DG8T4SFLoXcdPb_usXDVpVDe_WoFQ-e29haKq9ZItdltVlf_a9d_RQjRKqlfbdFmdDEP3DkGiWSs7z-1kdOiN1lTuT7uaR4NZvBqCaUsbblAsx3BdtAVXmfu6t8bTI9wy5lGbv",
      rating: 4.8,
      reviewCount: 120,
      priceRange: "€€€",
      priceLabel: "Fascia Alta",
      openTime: "19:30 - 23:00",
      philosophy: "Nel cuore pulsante del Cilento, La Dispensa di San Salvatore nasce come un omaggio alla terra. La nostra cucina celebra il concetto di \"farm-to-table\" autentico, portando in tavola solo ingredienti biologici coltivati direttamente nelle nostre tenute. Ogni piatto racconta la storia di un territorio generoso, dove la tradizione si fonde con una visione moderna della gastronomia mediterranea.",
      galleryImages: [
        { src: "https://lh3.googleusercontent.com/aida-public/AB6AXuC4e6gyjQEVcIAfcJNzX1_BQLUVkgeyZN-hLxyroXxvir7bF2RvYez6YsO0uDalb-TuDVEH1Zjy4rfVb9rJepo8wkNP6iKp4t7_DrJIwsgbUOEfkCYpoZcoS09Nf5ME1sG-lnOgga75VXa_6Sejo1LywuQ3PuLkgI0ZCCq4ddZFUkpXrG1sNyktxPyHBd0uonyS_WSx6ASiH_nE3bbC5IHMY9oJDqDJSbFciSQsXDV1kA34MX5gCq_8nawPL0ihni8Mx1ZmsJ2fYb0O", alt: "Mozzarella di bufala fresca", layout: "square" },
        { src: "https://lh3.googleusercontent.com/aida-public/AB6AXuCxYIsXBzDFK4K3PMms8BpvwDCoLSzJYN0EMEjE8aPZ1CGYDhosbkm69EkhhHoOHdg-8EH5Nwlm6jjBgpyYUV45HXmOQXQACjcggZ6e9zVGy5f2H0TIAj_wREdLVeENifdHh6N4PxlRdwzMKY_72oQnBtw8LcMiGalg8kz77l11d3mTC2gaALC3ztazHv-2bmQgt9vjJ_DH_gn2RCDBwvfSd5KCcWYYEPKtvbc0GXtt5FYdjozdQ_fm3QmYj6XuI6d5EJhsaS4fWLAI", alt: "Pasta fatta in casa con pomodoro", layout: "square" },
        { src: "https://lh3.googleusercontent.com/aida-public/AB6AXuD8yQnXPHhQP3voq6WbNmsLd6QL2Llv41HcB3eoaNQlNFGFOz8EDGl6igy2-SnOOA1IjYDqNxmLRyrAjZ4VVT1rsSjL_90aLOJuI3fWlDERXho99W75DhS_RX0WS4bPNFf8nrGVBYj7DLvmXnLH9AcWTTh1Pvq5p447nb9_5vc3fwzWd4WW4cbYMr6V4Q3bu90GHEjaXtaVMOqj2Jn_D-AqSq-4Yq5ujj94DU72mm6oXulLZfZ2GHQBRG9aX2Hx6EZxgFF8sehzxulj", alt: "Costolette d'agnello alle erbe", layout: "square" },
        { src: "https://lh3.googleusercontent.com/aida-public/AB6AXuA8u8DYcRpj5y-6ClzGRDLf1vhQTYR6tjre9S7m-Yl3AY1CSem92mqhxjYxm2T1pLVW2n7-qG-DjC8NAzcKOM7eqnh0ChRruhSzo3LWp-kHHJ7owCOMVR0jy4G3w0JJnUpfhdFfY2On9CdBOLjrgxOpr2WeOHG-M336QjIDu55F1G_2UPeG4YKC_PMDM_3gMOLh5l7eT4AjBEXv3jtHfW_KS98cMoXUw7spwH6ymb0GsUOy-xRMTU39taTbT9KEWrAn-uiEJcoKOTqO", alt: "Sala ristorante elegante", layout: "wide" },
        { src: "https://lh3.googleusercontent.com/aida-public/AB6AXuDkcBPV9M0p1-1tDO9uQXg4amqJ70s6KRefsbMAgSOb1BOMUtxFXSygoOmJTT8mwSGPAx786-FjYldg0Z9dKUMpx4Z05EmP4P75aJaUUSCpmvcxN-WuG2eptr2iPyJK7pnR3nCLDvaPdA2juPr8czO6COuyXYfLNNfs0Ldb7QeeZHUeIsWypLajof20xwr5L-bsktT5vdYTsIjUSm49x-T5V9XQl3ooXyksFmAyOlIhHJYQm6XY7LJteblszbiCFBKprsrK6rRg0aCV", alt: "Barman prepara un cocktail", layout: "overlay" },
      ],
      dishes: [
        { icon: "restaurant", name: "Mozzarella di Bufala DOP", description: "Produzione propria, servita con olio extravergine bio." },
        { icon: "dinner_dining", name: "Fusilli Cilentani", description: "Pasta fatta a mano con ragù di castrato tradizionale." },
        { icon: "set_meal", name: "Costolette d'Agnello", description: "Al timo selvatico, scottate su pietra lavica." },
      ],
      services: [
        { icon: "wifi", label: "WiFi Gratuito" },
        { icon: "local_parking", label: "Parcheggio Privato" },
        { icon: "air", label: "Aria Condizionata" },
      ],
      hours: [
        { day: "Lunedì", time: "Chiuso" },
        { day: "Mar - Dom", time: "12:30 - 15:00 / 19:30 - 23:00" },
      ],
      reviews: [
        { name: "Marco Rossini", avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuBJw9kkQl3SYSO0XzFKSOKWD9lgd8VnKRIJWWNuHHilmeVx6j7D187fbWsBCkxLg3nXzSpsWv2_UKjjex25px8M_OiEKcYV-nPQJnCF6r7pt4SnAqx1SsezmSiu3xGveFZ18g9dmgX-mj7Hn47QBXZHZhHcOj4_VW5RSWaiI-8uYCfFoM3NUKLyGXyFGIhak6zIXNMUiCWcJuJug8pIEvCK5OlARavqZAZy4iDu43jZcE8VUHlp0vieuGlZvz4CXeBxuhqdqCnGO71I", date: "14 Ottobre 2023", rating: 5, text: "Un'esperienza indimenticabile. La mozzarella di bufala è la migliore che abbia mai assaggiato. Personale gentilissimo e location mozzafiato." },
        { name: "Elena Bianchi", avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuBbIm96hKEKEW3IAZaIDyeh6eBgfUblnTXtJRzaHt8wQd2xa6NB3i_JM6ul_wAhPtwe68xyhNwtH8N8kTI7rbRHUfq0FdEQ9KgdoraTwagyoHLV4V-2sS1Konb1FllsGC8kSU1Yij3eB_zH9rKhJ2wYmWPpLhPXEOm3RdF-zc14DsqbP2cKOUoKigq30-rIJyHq1ynGOg5eBk0zlMY2U-dRTy9aLDmYasE0QxMAhZMFuRJkafYvSfTV6tEWzmgcMzTSHlOuimo7OygX", date: "28 Settembre 2023", rating: 4, text: "Posto incantevole tra gli ulivi. Piatti curati e materie prime d'eccellenza. Consiglio vivamente i fusilli." },
      ],
      mapImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuDdpxKJaXkGZzasBlsVCfCZBM6iv5Nr0FryQV8vTScdag_XsXLqPp3fO0INpdpDj3GXRkEDfSHbOjtaj84DwI6-3oSmxbiJj67xF1G2ZQ938SDhY7Hg6089brsMo9JrvovKRNgrKNv5dsV6m0P3GRdDnOZ5bwauDzmL8MTYtkjPFCx8r52B8wXJuVk-WUebMFgCK7eR8buXCvQSLy-tftif3JfMp-coUg9IxYa0_ooQCHIYUl-y7xeMjbciuWUAKARHRKXBEz8LDyvq",
    },
    {
      slug: "le-trabe",
      name: "Le Trabe",
      category: "ristorante",
      planType: "premium",
      location: "Paestum, Campania",
      description: "Gourmet & Fine Dining",
      cuisine: "Alta Cucina Mediterranea",
      badge: "Stella Michelin",
      badgeStyle: "bg-primary text-white",
      showOnHomepage: true,
      hasDetailPage: true,
      displayPriority: 2,
      featured: true,
      status: "published",
      image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDCiVNxSrBm3_loyFeuvoFOGDMFUup0uvn0CXrjgzgjEFgOasrKmOBEh-BRSvOGACBjN6UbdWLj-yeVbr3q87k4JL73jC2vSNBYgUEKRLwnq-zhOJTqcIZiNKPDEttPyC_I8jFEoO8Appfml_izxtyWq9KOnCNNdBHXLOeVynpzwExAsFVRXWdGS7_rDTbzkq5PUMpcLZ6Ltvaz5xNBhe3SDUhppDXOthalXmZTh4PL5Hj4uQXhPwaBr791MI9VQ5EOPk1a2XI8ggMn",
      heroImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuBLP3XiNJbEhDR1U7doj0EXcxdN6Nlfkj3ETN4PBfWJMe3u9y3mXC2hHrkvP-D39MhqKkv1c3ZkXYGDqbfpqJk1RNcjkXOGx5Skq9oE8PpBm6DwS9eyVU5XaAGzaiS6pmtaUbi-gVziL4gbPWl7BsxSboXwQlQm84MGg3hQg2k81DUe4IH7LbbaZKkFO81cvhMc0YmyKSUrS4wgpPk1HS4tSSw3lkiULC6LBTc75oFCVPlZMdR8UvHo_xetDMkhTBbQPK9bWsyK4YQi",
      rating: 4.9,
      reviewCount: 85,
      priceRange: "€€€€",
      priceLabel: "Fine Dining",
      openTime: "19:30 - 22:30",
      philosophy: "Le Trabe è un ristorante stellato Michelin immerso nella campagna di Paestum. Lo chef propone un viaggio sensoriale attraverso i sapori del Cilento, con tecniche d'avanguardia che esaltano la purezza delle materie prime locali. Ogni portata è un'opera d'arte che celebra il legame profondo tra terra e mare.",
      galleryImages: [
        { src: "https://lh3.googleusercontent.com/aida-public/AB6AXuDCiVNxSrBm3_loyFeuvoFOGDMFUup0uvn0CXrjgzgjEFgOasrKmOBEh-BRSvOGACBjN6UbdWLj-yeVbr3q87k4JL73jC2vSNBYgUEKRLwnq-zhOJTqcIZiNKPDEttPyC_I8jFEoO8Appfml_izxtyWq9KOnCNNdBHXLOeVynpzwExAsFVRXWdGS7_rDTbzkq5PUMpcLZ6Ltvaz5xNBhe3SDUhppDXOthalXmZTh4PL5Hj4uQXhPwaBr791MI9VQ5EOPk1a2XI8ggMn", alt: "Piatto gourmet stellato", layout: "square" },
        { src: "https://lh3.googleusercontent.com/aida-public/AB6AXuBLCxM9lGm4xn3TX4vIpN7_AqGibL3YLZaviPB5JWzeGMJANPMN-8cMLDtZKhrfdSSr_dkC8ZK1nEc2jehF3UsKM-vZQqTIZcp--_A5C_0wja52Qxw0XGvnZABCaMiDlC0hnp0ibN8eNpPuhjwM3WEKMYXGqIeyaMWU0PGDHMkz42PCOEQ4WdCfQIWPfs1lj_7MNyoFd5yUrVhSZdyIG_jE0BFCcfC8F3XuqNNtD0u5ISZx1o18YJIsEZ4nzM-lwdelRMqpImZObWnj", alt: "Dessert artistico", layout: "square" },
        { src: "https://lh3.googleusercontent.com/aida-public/AB6AXuCM68Wv0gCyxZnu5MTcZ8StCCx-riNU4tdfI31IAC-9PeHN0VCsZnj4Cqy9GrIjHfObFSE0OZ0MzDYUh-r8aHLaG4P9SSR7E99z96Vkmyrg1Q469zm4WH_bTbELRdkczViYJmh0DtEEqDvr_X7gct9uhP1qsA8YLs7Zw31DHMkkr7dVg3oqKEPk8Dzhzc4jZ91KFgTbowFBmzFxl6AP9iryADFlpHUS9yeAj51sirwHMO-1uenYL6pwiKJ3Ml_N9tMPYzYYibAypdCh", alt: "Terrazza panoramica", layout: "square" },
        { src: "https://lh3.googleusercontent.com/aida-public/AB6AXuA8u8DYcRpj5y-6ClzGRDLf1vhQTYR6tjre9S7m-Yl3AY1CSem92mqhxjYxm2T1pLVW2n7-qG-DjC8NAzcKOM7eqnh0ChRruhSzo3LWp-kHHJ7owCOMVR0jy4G3w0JJnUpfhdFfY2On9CdBOLjrgxOpr2WeOHG-M336QjIDu55F1G_2UPeG4YKC_PMDM_3gMOLh5l7eT4AjBEXv3jtHfW_KS98cMoXUw7spwH6ymb0GsUOy-xRMTU39taTbT9KEWrAn-uiEJcoKOTqO", alt: "Sala interna raffinata", layout: "wide" },
        { src: "https://lh3.googleusercontent.com/aida-public/AB6AXuDkcBPV9M0p1-1tDO9uQXg4amqJ70s6KRefsbMAgSOb1BOMUtxFXSygoOmJTT8mwSGPAx786-FjYldg0Z9dKUMpx4Z05EmP4P75aJaUUSCpmvcxN-WuG2eptr2iPyJK7pnR3nCLDvaPdA2juPr8czO6COuyXYfLNNfs0Ldb7QeeZHUeIsWypLajof20xwr5L-bsktT5vdYTsIjUSm49x-T5V9XQl3ooXyksFmAyOlIhHJYQm6XY7LJteblszbiCFBKprsrK6rRg0aCV", alt: "Cantina vini pregiati", layout: "overlay" },
      ],
      dishes: [
        { icon: "set_meal", name: "Crudo di Mare Cilentano", description: "Selezione di pesce crudo locale con agrumi e olio EVO." },
        { icon: "dinner_dining", name: "Ravioli di Ricotta di Bufala", description: "Con fonduta di Provolone del Monaco e tartufo nero." },
        { icon: "restaurant", name: "Filetto di Dentice", description: "Su crema di ceci di Cicerale e polvere di olive." },
      ],
      services: [
        { icon: "wifi", label: "WiFi Gratuito" },
        { icon: "local_parking", label: "Parcheggio Privato" },
        { icon: "air", label: "Aria Condizionata" },
      ],
      hours: [
        { day: "Lunedì - Martedì", time: "Chiuso" },
        { day: "Mer - Dom", time: "19:30 - 22:30" },
      ],
      reviews: [
        { name: "Giulia Ferraro", avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuBbIm96hKEKEW3IAZaIDyeh6eBgfUblnTXtJRzaHt8wQd2xa6NB3i_JM6ul_wAhPtwe68xyhNwtH8N8kTI7rbRHUfq0FdEQ9KgdoraTwagyoHLV4V-2sS1Konb1FllsGC8kSU1Yij3eB_zH9rKhJ2wYmWPpLhPXEOm3RdF-zc14DsqbP2cKOUoKigq30-rIJyHq1ynGOg5eBk0zlMY2U-dRTy9aLDmYasE0QxMAhZMFuRJkafYvSfTV6tEWzmgcMzTSHlOuimo7OygX", date: "5 Novembre 2023", rating: 5, text: "Esperienza gastronomica sublime. Ogni piatto è un capolavoro di sapori e presentazione. La stella Michelin è più che meritata." },
        { name: "Roberto Amato", avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuBJw9kkQl3SYSO0XzFKSOKWD9lgd8VnKRIJWWNuHHilmeVx6j7D187fbWsBCkxLg3nXzSpsWv2_UKjjex25px8M_OiEKcYV-nPQJnCF6r7pt4SnAqx1SsezmSiu3xGveFZ18g9dmgX-mj7Hn47QBXZHZhHcOj4_VW5RSWaiI-8uYCfFoM3NUKLyGXyFGIhak6zIXNMUiCWcJuJug8pIEvCK5OlARavqZAZy4iDu43jZcE8VUHlp0vieuGlZvz4CXeBxuhqdqCnGO71I", date: "20 Ottobre 2023", rating: 5, text: "Il menu degustazione è un viaggio incredibile nei sapori del Cilento. Servizio impeccabile e atmosfera magica." },
      ],
      mapImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuDdpxKJaXkGZzasBlsVCfCZBM6iv5Nr0FryQV8vTScdag_XsXLqPp3fO0INpdpDj3GXRkEDfSHbOjtaj84DwI6-3oSmxbiJj67xF1G2ZQ938SDhY7Hg6089brsMo9JrvovKRNgrKNv5dsV6m0P3GRdDnOZ5bwauDzmL8MTYtkjPFCx8r52B8wXJuVk-WUebMFgCK7eR8buXCvQSLy-tftif3JfMp-coUg9IxYa0_ooQCHIYUl-y7xeMjbciuWUAKARHRKXBEz8LDyvq",
    },
    {
      slug: "il-granato",
      name: "Il Granato",
      category: "caseificio",
      planType: "premium",
      location: "Capaccio, Campania",
      description: "Caseificio & Bistrò",
      cuisine: "Bistrò con Caseificio Artigianale",
      showOnHomepage: true,
      hasDetailPage: true,
      displayPriority: 3,
      featured: true,
      status: "published",
      image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDxBhqi0QWEmR85UJU0A00EIwbl_4sLybMN2Oyoky0TU7MslVx0eGPHEthy58rMcn2rU-G7BS9NlYLnw3ULdggrbhqrCOF4JKVhe_WdaE7LRF6YUW9y9cp44QCiT3JJFO1ZQXyKlvFEDtmKr8TQI553DeoAlNRC7ZTGlG1CwS0QLuDwjaLdd3YBwUJdGXWhvgNzP-jECA54lT4xP5oUr4dsP7QB2rWaQJUzQFgX9CppkSnoCo5lLM4-ms0aKOq7Yzs5vRyhJrJ6h_hk",
      heroImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuCM68Wv0gCyxZnu5MTcZ8StCCx-riNU4tdfI31IAC-9PeHN0VCsZnj4Cqy9GrIjHfObFSE0OZ0MzDYUh-r8aHLaG4P9SSR7E99z96Vkmyrg1Q469zm4WH_bTbELRdkczViYJmh0DtEEqDvr_X7gct9uhP1qsA8YLs7Zw31DHMkkr7dVg3oqKEPk8Dzhzc4jZ91KFgTbowFBmzFxl6AP9iryADFlpHUS9yeAj51sirwHMO-1uenYL6pwiKJ3Ml_N9tMPYzYYibAypdCh",
      rating: 4.6,
      reviewCount: 78,
      priceRange: "€€",
      priceLabel: "Fascia Media",
      openTime: "10:00 - 22:00",
      philosophy: "Il Granato unisce la tradizione casearia di Capaccio con la creatività di un bistrò moderno. Ogni giorno produciamo mozzarella, ricotta e formaggi freschi che diventano i protagonisti dei nostri piatti. Un'esperienza che parte dal laboratorio e arriva in tavola, dove i sapori autentici incontrano presentazioni contemporanee.",
      galleryImages: [
        { src: "https://lh3.googleusercontent.com/aida-public/AB6AXuDxBhqi0QWEmR85UJU0A00EIwbl_4sLybMN2Oyoky0TU7MslVx0eGPHEthy58rMcn2rU-G7BS9NlYLnw3ULdggrbhqrCOF4JKVhe_WdaE7LRF6YUW9y9cp44QCiT3JJFO1ZQXyKlvFEDtmKr8TQI553DeoAlNRC7ZTGlG1CwS0QLuDwjaLdd3YBwUJdGXWhvgNzP-jECA54lT4xP5oUr4dsP7QB2rWaQJUzQFgX9CppkSnoCo5lLM4-ms0aKOq7Yzs5vRyhJrJ6h_hk", alt: "Laboratorio caseario", layout: "square" },
        { src: "https://lh3.googleusercontent.com/aida-public/AB6AXuC4e6gyjQEVcIAfcJNzX1_BQLUVkgeyZN-hLxyroXxvir7bF2RvYez6YsO0uDalb-TuDVEH1Zjy4rfVb9rJepo8wkNP6iKp4t7_DrJIwsgbUOEfkCYpoZcoS09Nf5ME1sG-lnOgga75VXa_6Sejo1LywuQ3PuLkgI0ZCCq4ddZFUkpXrG1sNyktxPyHBd0uonyS_WSx6ASiH_nE3bbC5IHMY9oJDqDJSbFciSQsXDV1kA34MX5gCq_8nawPL0ihni8Mx1ZmsJ2fYb0O", alt: "Mozzarella fresca appena fatta", layout: "square" },
        { src: "https://lh3.googleusercontent.com/aida-public/AB6AXuCxYIsXBzDFK4K3PMms8BpvwDCoLSzJYN0EMEjE8aPZ1CGYDhosbkm69EkhhHoOHdg-8EH5Nwlm6jjBgpyYUV45HXmOQXQACjcggZ6e9zVGy5f2H0TIAj_wREdLVeENifdHh6N4PxlRdwzMKY_72oQnBtw8LcMiGalg8kz77l11d3mTC2gaALC3ztazHv-2bmQgt9vjJ_DH_gn2RCDBwvfSd5KCcWYYEPKtvbc0GXtt5FYdjozdQ_fm3QmYj6XuI6d5EJhsaS4fWLAI", alt: "Piatto del bistrò", layout: "square" },
        { src: "https://lh3.googleusercontent.com/aida-public/AB6AXuBWNzsawD_laLLp2VTmZFfFI_OGM7wiSJ6SAxHvNMUgfriHjXgaUrIW7jgHbDd475taZR6ztBuq0opb3xSSQOseSzUHTBfC-hwJ4Cm8kwev_cfqFC0Ib-0Frxw5rm-LNBUJD1E8f3DG8T4SFLoXcdPb_usXDVpVDe_WoFQ-e29haKq9ZItdltVlf_a9d_RQjRKqlfbdFmdDEP3DkGiWSs7z-1kdOiN1lTuT7uaR4NZvBqCaUsbblAsx3BdtAVXmfu6t8bTI9wy5lGbv", alt: "Tavoli all'aperto", layout: "wide" },
        { src: "https://lh3.googleusercontent.com/aida-public/AB6AXuD8yQnXPHhQP3voq6WbNmsLd6QL2Llv41HcB3eoaNQlNFGFOz8EDGl6igy2-SnOOA1IjYDqNxmLRyrAjZ4VVT1rsSjL_90aLOJuI3fWlDERXho99W75DhS_RX0WS4bPNFf8nrGVBYj7DLvmXnLH9AcWTTh1Pvq5p447nb9_5vc3fwzWd4WW4cbYMr6V4Q3bu90GHEjaXtaVMOqj2Jn_D-AqSq-4Yq5ujj94DU72mm6oXulLZfZ2GHQBRG9aX2Hx6EZxgFF8sehzxulj", alt: "Degustazione formaggi", layout: "overlay" },
      ],
      dishes: [
        { icon: "restaurant", name: "Treccia di Mozzarella", description: "Appena filata, con pomodorini del piennolo e basilico." },
        { icon: "dinner_dining", name: "Paccheri alla Sorrentina", description: "Con mozzarella filante e salsa di pomodoro San Marzano." },
        { icon: "set_meal", name: "Tagliere del Casaro", description: "Selezione di formaggi freschi e stagionati con miele locale." },
      ],
      services: [
        { icon: "local_parking", label: "Parcheggio Privato" },
        { icon: "child_care", label: "Area Bambini" },
        { icon: "deck", label: "Terrazza Esterna" },
      ],
      hours: [
        { day: "Lunedì", time: "Chiuso" },
        { day: "Mar - Dom", time: "10:00 - 15:00 / 18:00 - 22:00" },
      ],
      reviews: [
        { name: "Lucia Marino", avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuBbIm96hKEKEW3IAZaIDyeh6eBgfUblnTXtJRzaHt8wQd2xa6NB3i_JM6ul_wAhPtwe68xyhNwtH8N8kTI7rbRHUfq0FdEQ9KgdoraTwagyoHLV4V-2sS1Konb1FllsGC8kSU1Yij3eB_zH9rKhJ2wYmWPpLhPXEOm3RdF-zc14DsqbP2cKOUoKigq30-rIJyHq1ynGOg5eBk0zlMY2U-dRTy9aLDmYasE0QxMAhZMFuRJkafYvSfTV6tEWzmgcMzTSHlOuimo7OygX", date: "12 Novembre 2023", rating: 5, text: "La mozzarella più buona della zona! Poter vedere la produzione e poi degustarla è un'esperienza unica." },
        { name: "Andrea Conti", avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuBJw9kkQl3SYSO0XzFKSOKWD9lgd8VnKRIJWWNuHHilmeVx6j7D187fbWsBCkxLg3nXzSpsWv2_UKjjex25px8M_OiEKcYV-nPQJnCF6r7pt4SnAqx1SsezmSiu3xGveFZ18g9dmgX-mj7Hn47QBXZHZhHcOj4_VW5RSWaiI-8uYCfFoM3NUKLyGXyFGIhak6zIXNMUiCWcJuJug8pIEvCK5OlARavqZAZy4iDu43jZcE8VUHlp0vieuGlZvz4CXeBxuhqdqCnGO71I", date: "3 Ottobre 2023", rating: 4, text: "Ottimo rapporto qualità-prezzo. Ambiente informale ma curato. I paccheri sono da provare assolutamente." },
      ],
      mapImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuDdpxKJaXkGZzasBlsVCfCZBM6iv5Nr0FryQV8vTScdag_XsXLqPp3fO0INpdpDj3GXRkEDfSHbOjtaj84DwI6-3oSmxbiJj67xF1G2ZQ938SDhY7Hg6089brsMo9JrvovKRNgrKNv5dsV6m0P3GRdDnOZ5bwauDzmL8MTYtkjPFCx8r52B8wXJuVk-WUebMFgCK7eR8buXCvQSLy-tftif3JfMp-coUg9IxYa0_ooQCHIYUl-y7xeMjbciuWUAKARHRKXBEz8LDyvq",
    },
    {
      slug: "barlotti",
      name: "Barlotti",
      category: "ristorante",
      planType: "premium",
      location: "Battipaglia, Campania",
      description: "Specialità Bufalina",
      cuisine: "Specialità di Bufala Campana",
      showOnHomepage: true,
      hasDetailPage: true,
      displayPriority: 4,
      featured: true,
      status: "published",
      image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDuTPWP6CDCmB9tkllAdcH_qIVY0SI-tQ-ukR0vGOrv5y6wfGQLEVgONCXFxTwUmEKw1OTgpPMtqOnLXZL6luYQHe3ojNvtAMLmAkBhJZrZ9kc7BlBrNB2V2jPJN0fNYfr_fH3cyQYyjZLZnKc_1NWtgpSPH-cDmnonJeuzCfvo86EqzgzBPoqkjquIF1j8iU3o0qQgw17X2BLwvZ53R-7THwo7QlmIjBap8k8gtVB-5R82DZwzShV-89jTwdC8DZ4a_bpl6QAJhjaF",
      heroImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuBEvc5IyZbRNgFxO3MedUfOycyO5lB63OnsO488LA11wE08idIkFjAjzTYWV5CsqK05jMy_nlUqIYiKH39ecb9i1KWCy6CROpQlUadjVfy3Edi3CKH3lT75EkuyP2PF9sTINYX_BBx5F333k4hkA_qXmBnGpeNUfoSmKE8k6tPZuP-4SPjjfL7H-zzMe4zOj_nrIW28NdaWd_BdHDY-5Ny8DFQynb3Vq19ht_TapR0TQ4LEGfIZmWQUOqbi2t3D51VKv8Jcq4TwGXt3",
      rating: 4.5,
      reviewCount: 95,
      priceRange: "€€",
      priceLabel: "Fascia Media",
      openTime: "12:00 - 23:00",
      philosophy: "Barlotti è il tempio della bufala a Battipaglia, la capitale della mozzarella. Da tre generazioni la famiglia Barlotti seleziona il miglior latte di bufala per creare prodotti di eccellenza. Il ristorante nasce come naturale estensione del caseificio, dove ogni piatto celebra la versatilità di questo ingrediente straordinario.",
      galleryImages: [
        { src: "https://lh3.googleusercontent.com/aida-public/AB6AXuDuTPWP6CDCmB9tkllAdcH_qIVY0SI-tQ-ukR0vGOrv5y6wfGQLEVgONCXFxTwUmEKw1OTgpPMtqOnLXZL6luYQHe3ojNvtAMLmAkBhJZrZ9kc7BlBrNB2V2jPJN0fNYfr_fH3cyQYyjZLZnKc_1NWtgpSPH-cDmnonJeuzCfvo86EqzgzBPoqkjquIF1j8iU3o0qQgw17X2BLwvZ53R-7THwo7QlmIjBap8k8gtVB-5R82DZwzShV-89jTwdC8DZ4a_bpl6QAJhjaF", alt: "Bufala e mozzarella", layout: "square" },
        { src: "https://lh3.googleusercontent.com/aida-public/AB6AXuC4e6gyjQEVcIAfcJNzX1_BQLUVkgeyZN-hLxyroXxvir7bF2RvYez6YsO0uDalb-TuDVEH1Zjy4rfVb9rJepo8wkNP6iKp4t7_DrJIwsgbUOEfkCYpoZcoS09Nf5ME1sG-lnOgga75VXa_6Sejo1LywuQ3PuLkgI0ZCCq4ddZFUkpXrG1sNyktxPyHBd0uonyS_WSx6ASiH_nE3bbC5IHMY9oJDqDJSbFciSQsXDV1kA34MX5gCq_8nawPL0ihni8Mx1ZmsJ2fYb0O", alt: "Piatti a base di bufala", layout: "square" },
        { src: "https://lh3.googleusercontent.com/aida-public/AB6AXuD8yQnXPHhQP3voq6WbNmsLd6QL2Llv41HcB3eoaNQlNFGFOz8EDGl6igy2-SnOOA1IjYDqNxmLRyrAjZ4VVT1rsSjL_90aLOJuI3fWlDERXho99W75DhS_RX0WS4bPNFf8nrGVBYj7DLvmXnLH9AcWTTh1Pvq5p447nb9_5vc3fwzWd4WW4cbYMr6V4Q3bu90GHEjaXtaVMOqj2Jn_D-AqSq-4Yq5ujj94DU72mm6oXulLZfZ2GHQBRG9aX2Hx6EZxgFF8sehzxulj", alt: "Preparazione artigianale", layout: "square" },
        { src: "https://lh3.googleusercontent.com/aida-public/AB6AXuA8u8DYcRpj5y-6ClzGRDLf1vhQTYR6tjre9S7m-Yl3AY1CSem92mqhxjYxm2T1pLVW2n7-qG-DjC8NAzcKOM7eqnh0ChRruhSzo3LWp-kHHJ7owCOMVR0jy4G3w0JJnUpfhdFfY2On9CdBOLjrgxOpr2WeOHG-M336QjIDu55F1G_2UPeG4YKC_PMDM_3gMOLh5l7eT4AjBEXv3jtHfW_KS98cMoXUw7spwH6ymb0GsUOy-xRMTU39taTbT9KEWrAn-uiEJcoKOTqO", alt: "Sala del ristorante", layout: "wide" },
        { src: "https://lh3.googleusercontent.com/aida-public/AB6AXuDkcBPV9M0p1-1tDO9uQXg4amqJ70s6KRefsbMAgSOb1BOMUtxFXSygoOmJTT8mwSGPAx786-FjYldg0Z9dKUMpx4Z05EmP4P75aJaUUSCpmvcxN-WuG2eptr2iPyJK7pnR3nCLDvaPdA2juPr8czO6COuyXYfLNNfs0Ldb7QeeZHUeIsWypLajof20xwr5L-bsktT5vdYTsIjUSm49x-T5V9XQl3ooXyksFmAyOlIhHJYQm6XY7LJteblszbiCFBKprsrK6rRg0aCV", alt: "Area esterna panoramica", layout: "overlay" },
      ],
      dishes: [
        { icon: "restaurant", name: "Burrata di Bufala", description: "Cremosa e delicata, con cuore di stracciatella." },
        { icon: "dinner_dining", name: "Pizza Margherita DOC", description: "Con mozzarella di bufala DOP e pomodoro San Marzano." },
        { icon: "set_meal", name: "Carpaccio di Bufala", description: "Affumicato con rucola selvatica e riduzione di balsamico." },
      ],
      services: [
        { icon: "local_parking", label: "Parcheggio Gratuito" },
        { icon: "wifi", label: "WiFi Gratuito" },
        { icon: "groups", label: "Sale per Eventi" },
      ],
      hours: [
        { day: "Mercoledì", time: "Chiuso" },
        { day: "Lun - Mar, Gio - Dom", time: "12:00 - 15:00 / 18:30 - 23:00" },
      ],
      reviews: [
        { name: "Fabio D'Amico", avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuBJw9kkQl3SYSO0XzFKSOKWD9lgd8VnKRIJWWNuHHilmeVx6j7D187fbWsBCkxLg3nXzSpsWv2_UKjjex25px8M_OiEKcYV-nPQJnCF6r7pt4SnAqx1SsezmSiu3xGveFZ18g9dmgX-mj7Hn47QBXZHZhHcOj4_VW5RSWaiI-8uYCfFoM3NUKLyGXyFGIhak6zIXNMUiCWcJuJug8pIEvCK5OlARavqZAZy4iDu43jZcE8VUHlp0vieuGlZvz4CXeBxuhqdqCnGO71I", date: "8 Dicembre 2023", rating: 4, text: "La mozzarella è freschissima e si sente. Ambiente accogliente e personale cordiale. Torneremo sicuramente." },
        { name: "Valentina Russo", avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuBbIm96hKEKEW3IAZaIDyeh6eBgfUblnTXtJRzaHt8wQd2xa6NB3i_JM6ul_wAhPtwe68xyhNwtH8N8kTI7rbRHUfq0FdEQ9KgdoraTwagyoHLV4V-2sS1Konb1FllsGC8kSU1Yij3eB_zH9rKhJ2wYmWPpLhPXEOm3RdF-zc14DsqbP2cKOUoKigq30-rIJyHq1ynGOg5eBk0zlMY2U-dRTy9aLDmYasE0QxMAhZMFuRJkafYvSfTV6tEWzmgcMzTSHlOuimo7OygX", date: "22 Novembre 2023", rating: 5, text: "Il miglior posto per mangiare bufala a Battipaglia. La burrata è celestiale! Prezzi onesti per la qualità offerta." },
      ],
      mapImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuDdpxKJaXkGZzasBlsVCfCZBM6iv5Nr0FryQV8vTScdag_XsXLqPp3fO0INpdpDj3GXRkEDfSHbOjtaj84DwI6-3oSmxbiJj67xF1G2ZQ938SDhY7Hg6089brsMo9JrvovKRNgrKNv5dsV6m0P3GRdDnOZ5bwauDzmL8MTYtkjPFCx8r52B8wXJuVk-WUebMFgCK7eR8buXCvQSLy-tftif3JfMp-coUg9IxYa0_ooQCHIYUl-y7xeMjbciuWUAKARHRKXBEz8LDyvq",
    },
    {
      slug: "masseria-del-cilento",
      name: "Masseria del Cilento",
      category: "agriturismo",
      planType: "premium",
      location: "Capaccio, Campania",
      description: "Cucina contadina e ospitalità autentica",
      cuisine: "Agriturismo con Cucina Contadina",
      badge: "Consigliato",
      badgeStyle: "bg-white/90 backdrop-blur text-emerald-900",
      showOnHomepage: false,
      hasDetailPage: true,
      displayPriority: 5,
      featured: true,
      status: "published",
      phone: "+39 089 345 1234",
      website: "https://example.com",
      image: "https://lh3.googleusercontent.com/aida-public/AB6AXuC-Of56ZpLIjFT7KfqoYyRU9HVpJdy4OUeIdLu0WDnTSXpknfQsFSZ2wA1775zyWuySkjEGJfuqBT0PgKqkHQALavJmwKSExZZBcBKkka7S0LLtBMJcHqM3R2vpOKOlOtNKC--Ph5EL8wLNXxyZDPu-2XPjrOUf-s4hD3USQWhBiUvbH-IxrJqTnNTJvG2kUS9ANwQGGfe-Xctzc6bwV0Xl1duywKbHrZjyPwEoH48oA11dz5GkxgvkSLloUCFb3oFfZj6k9-2JOQD3",
      heroImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuC-Of56ZpLIjFT7KfqoYyRU9HVpJdy4OUeIdLu0WDnTSXpknfQsFSZ2wA1775zyWuySkjEGJfuqBT0PgKqkHQALavJmwKSExZZBcBKkka7S0LLtBMJcHqM3R2vpOKOlOtNKC--Ph5EL8wLNXxyZDPu-2XPjrOUf-s4hD3USQWhBiUvbH-IxrJqTnNTJvG2kUS9ANwQGGfe-Xctzc6bwV0Xl1duywKbHrZjyPwEoH48oA11dz5GkxgvkSLloUCFb3oFfZj6k9-2JOQD3",
      rating: 4.7,
      reviewCount: 62,
      priceRange: "€€",
      priceLabel: "Fascia Media",
      openTime: "12:00 - 22:00",
      philosophy: "La Masseria del Cilento è un agriturismo immerso nelle campagne di Capaccio. Qui si pratica ancora l'agricoltura tradizionale, e ogni piatto nasce dai prodotti dell'orto, del frutteto e dell'allevamento. Un'esperienza genuina, lontana dai ritmi della città.",
      galleryImages: [
        { src: "https://lh3.googleusercontent.com/aida-public/AB6AXuC-Of56ZpLIjFT7KfqoYyRU9HVpJdy4OUeIdLu0WDnTSXpknfQsFSZ2wA1775zyWuySkjEGJfuqBT0PgKqkHQALavJmwKSExZZBcBKkka7S0LLtBMJcHqM3R2vpOKOlOtNKC--Ph5EL8wLNXxyZDPu-2XPjrOUf-s4hD3USQWhBiUvbH-IxrJqTnNTJvG2kUS9ANwQGGfe-Xctzc6bwV0Xl1duywKbHrZjyPwEoH48oA11dz5GkxgvkSLloUCFb3oFfZj6k9-2JOQD3", alt: "Terrazza con vista campagna", layout: "wide" },
        { src: "https://lh3.googleusercontent.com/aida-public/AB6AXuBFdy4HmF5k4g2qPb_Zpv_fNdjxUDk3wLRscW2g8EPnuittz6-MjvL0kDAlaKwIbxeKFk7aDrShdEaz2BvHeXZnlCg3C1P3_6r82RF5RLQ8RS3p6dgOozYdVo24GPHU6lUhNUDfA4OHunWFMF4g-hBz2tz02jO07M66IqKcpQXiupkfiyTa2U2KPk_5oFWjoaE1HCvI5LIfZ7UKTzpp-ZqRRuEKYSggQziHGioDtu1T4aEsbd-iZICQ7JP1_zOR1ZO7SmFXTTepmADG", alt: "Prodotti dell'orto", layout: "square" },
      ],
      dishes: [
        { icon: "restaurant", name: "Cavatelli al Ragù", description: "Pasta fatta a mano con ragù di maiale nero cilentano." },
        { icon: "set_meal", name: "Frittura dell'Orto", description: "Verdure di stagione in pastella leggera." },
      ],
      services: [
        { icon: "local_parking", label: "Parcheggio Privato" },
        { icon: "deck", label: "Terrazza Panoramica" },
        { icon: "child_care", label: "Area Bambini" },
      ],
      hours: [
        { day: "Lunedì", time: "Chiuso" },
        { day: "Mar - Dom", time: "12:00 - 15:00 / 19:00 - 22:00" },
      ],
      reviews: [],
      mapImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuDdpxKJaXkGZzasBlsVCfCZBM6iv5Nr0FryQV8vTScdag_XsXLqPp3fO0INpdpDj3GXRkEDfSHbOjtaj84DwI6-3oSmxbiJj67xF1G2ZQ938SDhY7Hg6089brsMo9JrvovKRNgrKNv5dsV6m0P3GRdDnOZ5bwauDzmL8MTYtkjPFCx8r52B8wXJuVk-WUebMFgCK7eR8buXCvQSLy-tftif3JfMp-coUg9IxYa0_ooQCHIYUl-y7xeMjbciuWUAKARHRKXBEz8LDyvq",
    },
    // ── Basic listings ────────────────────────────────────────────
    {
      slug: "trattoria-da-maria",
      name: "Trattoria da Maria",
      category: "ristorante",
      planType: "basic",
      location: "Eboli, Campania",
      description: "Cucina casalinga della tradizione",
      cuisine: "Trattoria Tradizionale",
      phone: "+39 089 123 4567",
      website: "https://example.com",
      showOnHomepage: true,
      hasDetailPage: false,
      displayPriority: 10,
      featured: false,
      status: "published",
      image: "https://lh3.googleusercontent.com/aida-public/AB6AXuC4e6gyjQEVcIAfcJNzX1_BQLUVkgeyZN-hLxyroXxvir7bF2RvYez6YsO0uDalb-TuDVEH1Zjy4rfVb9rJepo8wkNP6iKp4t7_DrJIwsgbUOEfkCYpoZcoS09Nf5ME1sG-lnOgga75VXa_6Sejo1LywuQ3PuLkgI0ZCCq4ddZFUkpXrG1sNyktxPyHBd0uonyS_WSx6ASiH_nE3bbC5IHMY9oJDqDJSbFciSQsXDV1kA34MX5gCq_8nawPL0ihni8Mx1ZmsJ2fYb0O",
    },
    {
      slug: "pizzeria-vesuvio",
      name: "Pizzeria Vesuvio",
      category: "pizzeria",
      planType: "basic",
      location: "Battipaglia, Campania",
      description: "Pizza napoletana dal 1985",
      cuisine: "Pizzeria Napoletana",
      phone: "+39 089 234 5678",
      showOnHomepage: true,
      hasDetailPage: false,
      displayPriority: 11,
      featured: false,
      status: "published",
      image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCxYIsXBzDFK4K3PMms8BpvwDCoLSzJYN0EMEjE8aPZ1CGYDhosbkm69EkhhHoOHdg-8EH5Nwlm6jjBgpyYUV45HXmOQXQACjcggZ6e9zVGy5f2H0TIAj_wREdLVeENifdHh6N4PxlRdwzMKY_72oQnBtw8LcMiGalg8kz77l11d3mTC2gaALC3ztazHv-2bmQgt9vjJ_DH_gn2RCDBwvfSd5KCcWYYEPKtvbc0GXtt5FYdjozdQ_fm3QmYj6XuI6d5EJhsaS4fWLAI",
    },
    {
      slug: "agriturismo-le-colline",
      name: "Agriturismo Le Colline",
      category: "agriturismo",
      planType: "basic",
      location: "Capaccio, Campania",
      description: "Ospitalità rurale e prodotti tipici",
      cuisine: "Agriturismo con Cucina Tipica",
      phone: "+39 089 345 6789",
      website: "https://example.com",
      showOnHomepage: true,
      hasDetailPage: false,
      displayPriority: 12,
      featured: false,
      status: "published",
      image: "https://lh3.googleusercontent.com/aida-public/AB6AXuD8yQnXPHhQP3voq6WbNmsLd6QL2Llv41HcB3eoaNQlNFGFOz8EDGl6igy2-SnOOA1IjYDqNxmLRyrAjZ4VVT1rsSjL_90aLOJuI3fWlDERXho99W75DhS_RX0WS4bPNFf8nrGVBYj7DLvmXnLH9AcWTTh1Pvq5p447nb9_5vc3fwzWd4WW4cbYMr6V4Q3bu90GHEjaXtaVMOqj2Jn_D-AqSq-4Yq5ujj94DU72mm6oXulLZfZ2GHQBRG9aX2Hx6EZxgFF8sehzxulj",
    },
    {
      slug: "agriturismo-terra-madre",
      name: "Agriturismo Terra Madre",
      category: "agriturismo",
      planType: "basic",
      location: "Eboli, Campania",
      description: "Fattoria didattica e cucina biologica",
      cuisine: "Agriturismo Biologico",
      phone: "+39 089 345 9876",
      showOnHomepage: false,
      hasDetailPage: false,
      displayPriority: 16,
      featured: false,
      status: "published",
      image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDAkYSVFg_aNxZfjfmFOXaDGn6a7UIdyC0FCVDbMGciwiefXWu3ul2ODiWLnkhrdDE73f7ltgrI3Qn5obYHrlzN75S2Dbyi4Dr90M2FpnlWsDiCgOc967fcZsA_ivmAue8rBFFMiB7lonMHXQDXT3raxKxch2ckEBUgxNQ4VIhJor60dqTUOVPvB-Op4xfmFhm7OX640ccgsNXKCzRLkNAov7h6PUBp3WJGDEgQ27xw0i4cWMcLEOgbDnomcJKUe36oKogRs4mRK6NR",
    },
    {
      slug: "caseificio-la-perla",
      name: "Caseificio La Perla",
      category: "caseificio",
      planType: "basic",
      location: "Paestum, Campania",
      description: "Mozzarella di bufala artigianale",
      cuisine: "Caseificio Artigianale",
      phone: "+39 089 456 7890",
      showOnHomepage: true,
      hasDetailPage: false,
      displayPriority: 13,
      featured: false,
      status: "published",
      image: "https://lh3.googleusercontent.com/aida-public/AB6AXuA8u8DYcRpj5y-6ClzGRDLf1vhQTYR6tjre9S7m-Yl3AY1CSem92mqhxjYxm2T1pLVW2n7-qG-DjC8NAzcKOM7eqnh0ChRruhSzo3LWp-kHHJ7owCOMVR0jy4G3w0JJnUpfhdFfY2On9CdBOLjrgxOpr2WeOHG-M336QjIDu55F1G_2UPeG4YKC_PMDM_3gMOLh5l7eT4AjBEXv3jtHfW_KS98cMoXUw7spwH6ymb0GsUOy-xRMTU39taTbT9KEWrAn-uiEJcoKOTqO",
    },
    {
      slug: "cantina-del-sele",
      name: "Cantina del Sele",
      category: "cantina",
      planType: "basic",
      location: "Eboli, Campania",
      description: "Vini locali e degustazioni",
      cuisine: "Cantina Vinicola",
      phone: "+39 089 567 8901",
      website: "https://example.com",
      showOnHomepage: true,
      hasDetailPage: false,
      displayPriority: 14,
      featured: false,
      status: "published",
      image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDkcBPV9M0p1-1tDO9uQXg4amqJ70s6KRefsbMAgSOb1BOMUtxFXSygoOmJTT8mwSGPAx786-FjYldg0Z9dKUMpx4Z05EmP4P75aJaUUSCpmvcxN-WuG2eptr2iPyJK7pnR3nCLDvaPdA2juPr8czO6COuyXYfLNNfs0Ldb7QeeZHUeIsWypLajof20xwr5L-bsktT5vdYTsIjUSm49x-T5V9XQl3ooXyksFmAyOlIhHJYQm6XY7LJteblszbiCFBKprsrK6rRg0aCV",
    },
    {
      slug: "pasticceria-dolce-vita",
      name: "Pasticceria Dolce Vita",
      category: "pasticceria",
      planType: "basic",
      location: "Salerno, Campania",
      description: "Dolci della tradizione campana",
      cuisine: "Pasticceria Artigianale",
      phone: "+39 089 678 9012",
      showOnHomepage: true,
      hasDetailPage: false,
      displayPriority: 15,
      featured: false,
      status: "published",
      image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBLP3XiNJbEhDR1U7doj0EXcxdN6Nlfkj3ETN4PBfWJMe3u9y3mXC2hHrkvP-D39MhqKkv1c3ZkXYGDqbfpqJk1RNcjkXOGx5Skq9oE8PpBm6DwS9eyVU5XaAGzaiS6pmtaUbi-gVziL4gbPWl7BsxSboXwQlQm84MGg3hQg2k81DUe4IH7LbbaZKkFO81cvhMc0YmyKSUrS4wgpPk1HS4tSSw3lkiULC6LBTc75oFCVPlZMdR8UvHo_xetDMkhTBbQPK9bWsyK4YQi",
    },
  ];

  for (const listing of listings) {
    await prisma.listing.upsert({
      where: { slug: listing.slug },
      update: listing,
      create: listing,
    });
  }
  console.log(`✅ ${listings.length} listings seeded`);

  // ── Artists ──────────────────────────────────────────────────────────
  const artistsData = [
    {
      slug: "marco-russo",
      name: "Marco Russo",
      artistType: "cantante",
      genre: "Jazz & Soul",
      location: "Paestum",
      planType: "premium",
      hasDetailPage: true,
      showOnHomepage: true,
      displayPriority: 1,
      featured: true,
      status: "published",
      shortDescription: "Vocalist jazz con oltre 15 anni di esperienza in eventi esclusivi nella Piana del Sele.",
      biography: "Marco Russo è un vocalist jazz nato e cresciuto a Paestum. Dopo gli studi al Conservatorio di Salerno, ha affinato il suo stile esibendosi nei club jazz di tutta Italia. La sua voce calda e avvolgente lo ha reso uno degli artisti più richiesti per matrimoni ed eventi di alto livello nella Piana del Sele. Collabora regolarmente con musicisti internazionali e ha all'attivo due album di brani originali ispirati alla tradizione musicale campana rivisitata in chiave jazz.",
      musicStyle: "Un blend sofisticato di jazz classico, soul e influenze della musica mediterranea. Repertorio che spazia da Frank Sinatra a Michael Bublé, passando per brani originali.",
      image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDdlve7VM-C__4ama0CZ1w06m-q1GuDL61eYrChAEfkz2sc-yEdQwjBJbdLeiAvfba48fP2DNqGRlcHXCJFpQCeTAuABNWJF4fTnvId6WGc7j0UmbNiRysfcKrgeflsuNr9yu7iKeBJ74mC9oQ_I5LWRtW3HOAINOmvBsRa14wZ5wlRbVZaKOT6Tq42E8Jvyw088_kQoRVJaULOCSydL9j9oRvOiexxrAliubLi6Q-T2xTUcFe3N-8Bf9iiqcr8kXXudu7JBh8HUGsm",
      galleryImages: [
        { src: "https://lh3.googleusercontent.com/aida-public/AB6AXuDCiVNxSrBm3_loyFeuvoFOGDMFUup0uvn0CXrjgzgjEFgOasrKmOBEh-BRSvOGACBjN6UbdWLj-yeVbr3q87k4JL73jC2vSNBYgUEKRLwnq-zhOJTqcIZiNKPDEttPyC_I8jFEoO8Appfml_izxtyWq9KOnCNNdBHXLOeVynpzwExAsFVRXWdGS7_rDTbzkq5PUMpcLZ6Ltvaz5xNBhe3SDUhppDXOthalXmZTh4PL5Hj4uQXhPwaBr791MI9VQ5EOPk1a2XI8ggMn", alt: "Performance live" },
        { src: "https://lh3.googleusercontent.com/aida-public/AB6AXuDxBhqi0QWEmR85UJU0A00EIwbl_4sLybMN2Oyoky0TU7MslVx0eGPHEthy58rMcn2rU-G7BS9NlYLnw3ULdggrbhqrCOF4JKVhe_WdaE7LRF6YUW9y9cp44QCiT3JJFO1ZQXyKlvFEDtmKr8TQI553DeoAlNRC7ZTGlG1CwS0QLuDwjaLdd3YBwUJdGXWhvgNzP-jECA54lT4xP5oUr4dsP7QB2rWaQJUzQFgX9CppkSnoCo5lLM4-ms0aKOq7Yzs5vRyhJrJ6h_hk", alt: "Studio di registrazione" },
        { src: "https://lh3.googleusercontent.com/aida-public/AB6AXuDuTPWP6CDCmB9tkllAdcH_qIVY0SI-tQ-ukR0vGOrv5y6wfGQLEVgONCXFxTwUmEKw1OTgpPMtqOnLXZL6luYQHe3ojNvtAMLmAkBhJZrZ9kc7BlBrNB2V2jPJN0fNYfr_fH3cyQYyjZLZnKc_1NWtgpSPH-cDmnonJeuzCfvo86EqzgzBPoqkjquIF1j8iU3o0qQgw17X2BLwvZ53R-7THwo7QlmIjBap8k8gtVB-5R82DZwzShV-89jTwdC8DZ4a_bpl6QAJhjaF", alt: "Evento privato" },
      ],
      videoEmbeds: [
        { url: "https://www.youtube.com/embed/dQw4w9WgXcQ", title: "Live al Jazz Club Salerno" },
        { url: "https://www.youtube.com/embed/dQw4w9WgXcQ", title: "Fly Me to the Moon - Cover" },
      ],
      socialLinks: [
        { platform: "instagram", url: "https://instagram.com" },
        { platform: "facebook", url: "https://facebook.com" },
        { platform: "spotify", url: "https://spotify.com" },
      ],
      eventTypes: ["Matrimoni", "Cene Private", "Aperitivi"],
    },
    {
      slug: "anna-esposito",
      name: "Anna Esposito",
      artistType: "cantante",
      genre: "Musica Napoletana",
      location: "Salerno",
      planType: "premium",
      hasDetailPage: true,
      showOnHomepage: true,
      displayPriority: 2,
      featured: true,
      status: "published",
      shortDescription: "Interprete appassionata della grande tradizione musicale napoletana, perfetta per eventi autentici.",
      biography: "Anna Esposito porta avanti con orgoglio la tradizione della musica napoletana. Cresciuta tra le melodie dei grandi classici, ha studiato canto lirico prima di dedicarsi completamente alla musica popolare. Le sue interpretazioni di brani storici, da 'O Sole Mio a Napule è, emozionano il pubblico di ogni età.",
      musicStyle: "Musica napoletana classica e contemporanea. Repertorio che include i grandi classici di Murolo, Carosone e De André napoletano, fino alle hit moderne di Pino Daniele e Gigi D'Alessio.",
      image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBFdy4HmF5k4g2qPb_Zpv_fNdjxUDk3wLRscW2g8EPnuittz6-MjvL0kDAlaKwIbxeKFk7aDrShdEaz2BvHeXZnlCg3C1P3_6r82RF5RLQ8RS3p6dgOozYdVo24GPHU6lUhNUDfA4OHunWFMF4g-hBz2tz02jO07M66IqKcpQXiupkfiyTa2U2KPk_5oFWjoaE1HCvI5LIfZ7UKTzpp-ZqRRuEKYSggQziHGioDtu1T4aEsbd-iZICQ7JP1_zOR1ZO7SmFXTTepmADG",
      galleryImages: [
        { src: "https://lh3.googleusercontent.com/aida-public/AB6AXuDAkYSVFg_aNxZfjfmFOXaDGn6a7UIdyC0FCVDbMGciwiefXWu3ul2ODiWLnkhrdDE73f7ltgrI3Qn5obYHrlzN75S2Dbyi4Dr90M2FpnlWsDiCgOc967fcZsA_ivmAue8rBFFMiB7lonMHXQDXT3raxKxch2ckEBUgxNQ4VIhJor60dqTUOVPvB-Op4xfmFhm7OX640ccgsNXKCzRLkNAov7h6PUBp3WJGDEgQ27xw0i4cWMcLEOgbDnomcJKUe36oKogRs4mRK6NR", alt: "Performance dal vivo" },
        { src: "https://lh3.googleusercontent.com/aida-public/AB6AXuC-Of56ZpLIjFT7KfqoYyRU9HVpJdy4OUeIdLu0WDnTSXpknfQsFSZ2wA1775zyWuySkjEGJfuqBT0PgKqkHQALavJmwKSExZZBcBKkka7S0LLtBMJcHqM3R2vpOKOlOtNKC--Ph5EL8wLNXxyZDPu-2XPjrOUf-s4hD3USQWhBiUvbH-IxrJqTnNTJvG2kUS9ANwQGGfe-Xctzc6bwV0Xl1duywKbHrZjyPwEoH48oA11dz5GkxgvkSLloUCFb3oFfZj6k9-2JOQD3", alt: "Concerto" },
      ],
      videoEmbeds: [{ url: "https://www.youtube.com/embed/dQw4w9WgXcQ", title: "O Sole Mio - Live Performance" }],
      socialLinks: [
        { platform: "instagram", url: "https://instagram.com" },
        { platform: "youtube", url: "https://youtube.com" },
      ],
      eventTypes: ["Matrimoni", "Sagre & Festival", "Cene Private"],
    },
    {
      slug: "luca-de-luca",
      name: "Luca De Luca",
      artistType: "band",
      genre: "Pop & Rock",
      location: "Battipaglia",
      planType: "premium",
      hasDetailPage: true,
      showOnHomepage: true,
      displayPriority: 3,
      featured: true,
      status: "published",
      shortDescription: "Band leader versatile, dalle cover rock agli ultimi successi pop italiani e internazionali.",
      biography: "Luca De Luca è il frontman della band più richiesta della Piana del Sele. Con la sua energia contagiosa e un repertorio vastissimo, trasforma ogni evento in una festa indimenticabile.",
      musicStyle: "Pop, rock e dance music italiana e internazionale. Dai classici di Vasco Rossi e Ligabue ai successi di Ed Sheeran e Bruno Mars.",
      image: "https://lh3.googleusercontent.com/aida-public/AB6AXuC1A0AYFljePFn_7qZIP9P-X9Tfx5P8JywPHELjDxyMSXrk9trPp8nxNrbuT0CJtJLmuQ_KDpnf3dg7g8BRAUnC9ctvPfMIt0dn6do0NYcN5cLpY7k0L8wsi9maMbwaNV8ZxKLp3Ggs1Cz7OEIjub-yFOk18IGwtdBiNqZlKp7yEOpfKu8I932qbm7EUN0ooGF4fNKu7VmlW3SFWZvF3nTAN-Lnhjm_XcFwec55U5AqvdeGTsKogwlIZ4A1bwDCe9D30_rexj_k4z9x",
      galleryImages: [
        { src: "https://lh3.googleusercontent.com/aida-public/AB6AXuBWHPUcA09DRK0n2vIGECnxe_vMlqYVJi6UKMFjU74UEX2sZqt4GA02ycCkOfpER33PY7Cm-aK11ZdQvD653-tDXUqLgpjomGthPTOSJR3hMr0WnX9RGdLBQIQqMlmguEn-o1miCj3uMTEJIWdbwNavC1ikEUW5jaCSOarN9wFMQGLF6auhkUa9Lgh0IkzYeekX71zSjbooNl5Jf7larekcdg4mTqFfDCrVykVuFVZmURRTMP76wwhF7Hyfh7r0gGkYdFNxO3MXz6Jx", alt: "Live performance" },
        { src: "https://lh3.googleusercontent.com/aida-public/AB6AXuCyRAg0wANgrpOyBs8dhEuS7SmL0J8t2VtNDX8DNYJWQHbAtRdOd0esgLIzql22_vmsizvW0E7fX2IuB4mSRM5jW3zC3l9tRQaXthRbFaxsM1FKO_8tnNsEyel1GHJ6ZhCkKw4-bVgU0sKnSR9q6HTKMVOSxXbKcpY1J50bY5oxePlqI87zSRaY_9RzN_Pz8zM6e--T5CO2y0lbOpqR9lsno8b-bzmuQzmy80_7CtSpalT5ul9xSpbUR4sDzv3r-HpDirGmW8nqZExN", alt: "Backstage" },
      ],
      videoEmbeds: [
        { url: "https://www.youtube.com/embed/dQw4w9WgXcQ", title: "Medley Rock Italiano - Live" },
        { url: "https://www.youtube.com/embed/dQw4w9WgXcQ", title: "Wedding Highlight Reel" },
      ],
      socialLinks: [
        { platform: "instagram", url: "https://instagram.com" },
        { platform: "facebook", url: "https://facebook.com" },
        { platform: "youtube", url: "https://youtube.com" },
        { platform: "tiktok", url: "https://tiktok.com" },
      ],
      eventTypes: ["Matrimoni", "Feste Aziendali", "Eventi all'Aperto"],
    },
    {
      slug: "dj-salvatore",
      name: "DJ Salvatore",
      artistType: "dj",
      genre: "DJ Set",
      location: "Eboli",
      planType: "premium",
      hasDetailPage: true,
      showOnHomepage: true,
      displayPriority: 4,
      featured: true,
      status: "published",
      shortDescription: "DJ professionista specializzato in set per aperitivi, feste private e serate danzanti.",
      biography: "DJ Salvatore è il punto di riferimento per la musica elettronica nella Piana del Sele. Con oltre 10 anni di esperienza, è specializzato in set personalizzati che si adattano perfettamente all'atmosfera di ogni evento.",
      musicStyle: "Deep house, lounge, disco e commercial dance. Set personalizzati per ogni tipo di evento.",
      image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAbfzZRETVO7NFS4aS_O496ZeR1Ad50cGC6U_lIfP7eiflXht-yewEJ7yd6tbpTM-I6BSMxBdVq_e_S-i0_if9MZI466tS4zL5bEdB-iHmsRdGyJjvu1TBtSNB4Yew_Yp09hsyVYBlJhfkwrS8IrUHiTG5Zwlf3nQii81iOfDMDk0q9MydNbD5fn7bHoC5Pg9f1Ot6LuReewolnJaAahKLyVV-Pm_yYouIJGbRWV0cl9IUDmrFvtF2d4WwrI7PEQzn-VPnvDUdfzOtR",
      galleryImages: [{ src: "https://lh3.googleusercontent.com/aida-public/AB6AXuBnSaOr6CNBFQKRdi-IW6KLoRvItzBuo5hrgumXlpv2Adm-OKAJcAAK92gtVY4-jDgvnLz4x7NPPekpfu4DyICelyGsQQsK1wbeqgeTJtOLFBfmTlcUC3qNb2qGktbvkR8nNlB0baX58aYBzCCYZOn3QmMNtgFmn_EPZuF83z7bksDXgNcmFdZCi12VGP-a_upnGNnQWiLbIr2Ou5BGxG0AQe5664fK_Q2zVNPqsT5aeym_CTU---UX6slTEGU82XuidACXtLZiHRbx", alt: "DJ Set" }],
      videoEmbeds: [{ url: "https://www.youtube.com/embed/dQw4w9WgXcQ", title: "Summer Sunset Set - Paestum Beach" }],
      socialLinks: [
        { platform: "instagram", url: "https://instagram.com" },
        { platform: "spotify", url: "https://spotify.com" },
      ],
      eventTypes: ["Aperitivi", "Feste Aziendali", "Eventi all'Aperto"],
    },
    {
      slug: "elena-ferrara",
      name: "Elena Ferrara",
      artistType: "musicista",
      genre: "Musica Classica",
      location: "Capaccio",
      planType: "premium",
      hasDetailPage: true,
      showOnHomepage: false,
      displayPriority: 5,
      featured: false,
      status: "published",
      shortDescription: "Violinista classica di formazione, porta eleganza raffinata a cerimonie e ricevimenti.",
      biography: "Elena Ferrara è una violinista di talento formatasi al Conservatorio San Pietro a Majella di Napoli. Dopo anni di esperienza in orchestre sinfoniche, ha scelto di dedicarsi alla musica per eventi.",
      musicStyle: "Musica classica, colonne sonore e crossover. Repertorio che include Bach, Vivaldi, Einaudi, Morricone.",
      image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCmmiRpr1i2UTs-WirR9CDVE_z52V_jf2WuDzXHH5U6KoI3DNnQXIFisXszsmw9HPhiEl_2MW-WQuT79aarLEpnhLjDz_AHUaWEDUEgxUjprCpdOnGfWxNgkVHLpilg8s1jeA9H-Vgjm_qGDLwx1ITTb69OKkdRDtQUons_C8my3vVK1B5IM75ik9wBSQznqTaagtJZrEyY6Wir2WtoVi_NePZ6ZrFYYkcQ-zLd659NJHNrJhtrGr34l_6bqDLmxV5YW5UQx1al0JfD",
      galleryImages: [
        { src: "https://lh3.googleusercontent.com/aida-public/AB6AXuDdlve7VM-C__4ama0CZ1w06m-q1GuDL61eYrChAEfkz2sc-yEdQwjBJbdLeiAvfba48fP2DNqGRlcHXCJFpQCeTAuABNWJF4fTnvId6WGc7j0UmbNiRysfcKrgeflsuNr9yu7iKeBJ74mC9oQ_I5LWRtW3HOAINOmvBsRa14wZ5wlRbVZaKOT6Tq42E8Jvyw088_kQoRVJaULOCSydL9j9oRvOiexxrAliubLi6Q-T2xTUcFe3N-8Bf9iiqcr8kXXudu7JBh8HUGsm", alt: "Concerto di violino" },
        { src: "https://lh3.googleusercontent.com/aida-public/AB6AXuDCiVNxSrBm3_loyFeuvoFOGDMFUup0uvn0CXrjgzgjEFgOasrKmOBEh-BRSvOGACBjN6UbdWLj-yeVbr3q87k4JL73jC2vSNBYgUEKRLwnq-zhOJTqcIZiNKPDEttPyC_I8jFEoO8Appfml_izxtyWq9KOnCNNdBHXLOeVynpzwExAsFVRXWdGS7_rDTbzkq5PUMpcLZ6Ltvaz5xNBhe3SDUhppDXOthalXmZTh4PL5Hj4uQXhPwaBr791MI9VQ5EOPk1a2XI8ggMn", alt: "Cerimonia" },
      ],
      videoEmbeds: [{ url: "https://www.youtube.com/embed/dQw4w9WgXcQ", title: "Concerto per Violino" }],
      socialLinks: [
        { platform: "instagram", url: "https://instagram.com" },
        { platform: "youtube", url: "https://youtube.com" },
      ],
      eventTypes: ["Matrimoni", "Cene Private", "Aperitivi"],
    },
    {
      slug: "tony-cilento",
      name: "Tony Cilento",
      artistType: "musicista",
      genre: "Folk & Tradizionale",
      location: "Agropoli",
      planType: "premium",
      hasDetailPage: true,
      showOnHomepage: false,
      displayPriority: 6,
      featured: false,
      status: "published",
      shortDescription: "Musicista folk che celebra le tradizioni musicali del Cilento con tamburello e chitarra battente.",
      biography: "Tony Cilento è un musicista folk che ha dedicato la sua vita alla preservazione della tradizione musicale cilentana. Suona chitarra battente, tamburello e organetto.",
      musicStyle: "Musica folk cilentana e del sud Italia. Tarantelle, pizziche, villanelle e canti della tradizione contadina.",
      image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDCIzWJuRfMbRDrHetzmCGaEWJf5SW-MBK7rvE2LFn_96T8aXMcog7UIicLiTgrgH7M0q0eisa6LdQr8a3Bla8w_RNFaFdwpSfBkvV-rlqQICmGmPDTP_z51NQqTopSD6BWBb8raXwkqkAsNx3FU_vWG-_hhgfdU8obpmDPcljPgBxLSbQPFjqXrPfD1WqAdmdqDYsTaBc3eF-jw5TjndNatLrIxhAAdwvZ4LLUkPLhQ9k9mKaaaZnVUpY1I8tHbxOhzK6a51tqoRuV",
      galleryImages: [
        { src: "https://lh3.googleusercontent.com/aida-public/AB6AXuBFdy4HmF5k4g2qPb_Zpv_fNdjxUDk3wLRscW2g8EPnuittz6-MjvL0kDAlaKwIbxeKFk7aDrShdEaz2BvHeXZnlCg3C1P3_6r82RF5RLQ8RS3p6dgOozYdVo24GPHU6lUhNUDfA4OHunWFMF4g-hBz2tz02jO07M66IqKcpQXiupkfiyTa2U2KPk_5oFWjoaE1HCvI5LIfZ7UKTzpp-ZqRRuEKYSggQziHGioDtu1T4aEsbd-iZICQ7JP1_zOR1ZO7SmFXTTepmADG", alt: "Concerto folk" },
        { src: "https://lh3.googleusercontent.com/aida-public/AB6AXuC-Of56ZpLIjFT7KfqoYyRU9HVpJdy4OUeIdLu0WDnTSXpknfQsFSZ2wA1775zyWuySkjEGJfuqBT0PgKqkHQALavJmwKSExZZBcBKkka7S0LLtBMJcHqM3R2vpOKOlOtNKC--Ph5EL8wLNXxyZDPu-2XPjrOUf-s4hD3USQWhBiUvbH-IxrJqTnNTJvG2kUS9ANwQGGfe-Xctzc6bwV0Xl1duywKbHrZjyPwEoH48oA11dz5GkxgvkSLloUCFb3oFfZj6k9-2JOQD3", alt: "Sagra" },
        { src: "https://lh3.googleusercontent.com/aida-public/AB6AXuC1A0AYFljePFn_7qZIP9P-X9Tfx5P8JywPHELjDxyMSXrk9trPp8nxNrbuT0CJtJLmuQ_KDpnf3dg7g8BRAUnC9ctvPfMIt0dn6do0NYcN5cLpY7k0L8wsi9maMbwaNV8ZxKLp3Ggs1Cz7OEIjub-yFOk18IGwtdBiNqZlKp7yEOpfKu8I932qbm7EUN0ooGF4fNKu7VmlW3SFWZvF3nTAN-Lnhjm_XcFwec55U5AqvdeGTsKogwlIZ4A1bwDCe9D30_rexj_k4z9x", alt: "Festival" },
      ],
      videoEmbeds: [
        { url: "https://www.youtube.com/embed/dQw4w9WgXcQ", title: "Tarantella Cilentana" },
        { url: "https://www.youtube.com/embed/dQw4w9WgXcQ", title: "Intervista Tradizioni Musicali" },
      ],
      socialLinks: [
        { platform: "facebook", url: "https://facebook.com" },
        { platform: "youtube", url: "https://youtube.com" },
      ],
      eventTypes: ["Sagre & Festival", "Eventi all'Aperto", "Matrimoni"],
    },
    // ── Basic artists ─────────────────────────────────────────────
    {
      slug: "duo-acoustic-sele",
      name: "Duo Acoustic Sele",
      artistType: "band",
      genre: "Pop & Rock",
      location: "Salerno",
      planType: "basic",
      hasDetailPage: false,
      showOnHomepage: true,
      displayPriority: 10,
      featured: false,
      status: "published",
      shortDescription: "Duo acustico per aperitivi e cene eleganti. Chitarra e voce con repertorio italiano e internazionale.",
      image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBWHPUcA09DRK0n2vIGECnxe_vMlqYVJi6UKMFjU74UEX2sZqt4GA02ycCkOfpER33PY7Cm-aK11ZdQvD653-tDXUqLgpjomGthPTOSJR3hMr0WnX9RGdLBQIQqMlmguEn-o1miCj3uMTEJIWdbwNavC1ikEUW5jaCSOarN9wFMQGLF6auhkUa9Lgh0IkzYeekX71zSjbooNl5Jf7larekcdg4mTqFfDCrVykVuFVZmURRTMP76wwhF7Hyfh7r0gGkYdFNxO3MXz6Jx",
      eventTypes: ["Aperitivi", "Cene Private"],
      phone: "+39 333 123 4567",
    },
    {
      slug: "dj-niko",
      name: "DJ Niko",
      artistType: "dj",
      genre: "DJ Set",
      location: "Battipaglia",
      planType: "basic",
      hasDetailPage: false,
      showOnHomepage: true,
      displayPriority: 11,
      featured: false,
      status: "published",
      shortDescription: "DJ per feste private e eventi aziendali. Specializzato in musica anni 80-90 e commercial.",
      image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCyRAg0wANgrpOyBs8dhEuS7SmL0J8t2VtNDX8DNYJWQHbAtRdOd0esgLIzql22_vmsizvW0E7fX2IuB4mSRM5jW3zC3l9tRQaXthRbFaxsM1FKO_8tnNsEyel1GHJ6ZhCkKw4-bVgU0sKnSR9q6HTKMVOSxXbKcpY1J50bY5oxePlqI87zSRaY_9RzN_Pz8zM6e--T5CO2y0lbOpqR9lsno8b-bzmuQzmy80_7CtSpalT5ul9xSpbUR4sDzv3r-HpDirGmW8nqZExN",
      eventTypes: ["Feste Aziendali", "Aperitivi", "Eventi all'Aperto"],
      phone: "+39 333 234 5678",
      website: "https://example.com",
    },
    {
      slug: "carmen-vocalist",
      name: "Carmen Vocalist",
      artistType: "cantante",
      genre: "Musica Napoletana",
      location: "Eboli",
      planType: "basic",
      hasDetailPage: false,
      showOnHomepage: true,
      displayPriority: 12,
      featured: false,
      status: "published",
      shortDescription: "Cantante per cerimonie e ricevimenti. Repertorio classico napoletano e italiano.",
      image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAbfzZRETVO7NFS4aS_O496ZeR1Ad50cGC6U_lIfP7eiflXht-yewEJ7yd6tbpTM-I6BSMxBdVq_e_S-i0_if9MZI466tS4zL5bEdB-iHmsRdGyJjvu1TBtSNB4Yew_Yp09hsyVYBlJhfkwrS8IrUHiTG5Zwlf3nQii81iOfDMDk0q9MydNbD5fn7bHoC5Pg9f1Ot6LuReewolnJaAahKLyVV-Pm_yYouIJGbRWV0cl9IUDmrFvtF2d4WwrI7PEQzn-VPnvDUdfzOtR",
      eventTypes: ["Matrimoni", "Cene Private", "Sagre & Festival"],
      phone: "+39 333 345 6789",
    },
  ];

  for (const artist of artistsData) {
    await prisma.artist.upsert({
      where: { slug: artist.slug },
      update: artist,
      create: artist,
    });
  }
  console.log(`✅ ${artistsData.length} artists seeded`);

  console.log("🌱 Seeding complete!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
